#! /bin/sh
#
# Example panel for LemonBoy's bar

. $HOME/bin/colr

num_mon=$(bspc query -M | wc -l)
Padding=" "

while read -r line ; do
	case $line in
		D*)
			# Date Output
			date=" $Padding${line#?}$Padding"
			;;
		R*)
			# MPD Output
			music="%{A:albumart.sh:}%{A3:mpc toggle:}${line#?}%{A}%{A}"
			;;
		C*)
			# Clock Output
			clock="$Padding${line#?}$Padding"
			;;
		B*)
			# Battery Output
			battery="${line#?}"
			;;
		T*)
			# Xtitle Output
			title="${line#?}$Padding$Padding"
			;;

		V*)
			# Alsa Volume
			volume="%{A3:amixer set Master toggle:}%{A4:amixer set Master 5%+:}%{A5:amixer set Master 5%-:}%{B#$magenta}$Padding${line#?}$Padding%{B-}%{A}%{A}%{A}"
			;;
		L*)
			# Wifi Link
			wifi="$Padding${line#?}$Padding"
			;;
		Z*)
			# Power
			power="%{A3:albumart.sh:}${line#?}%{A}"
			;;

		W*)
			# BSPWM Workspaces
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					M*)
						# Active Monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="$wm_infos %{F#$purewhite}%{B#$purewhite}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}  "
						fi
						;;
					m*)
						# Inactive Monitor
						if [ $num_mon -gt 1 ] ; then
							wm_infos="${wm_infos}%{F#$bg}%{B#$bg}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}  "
						fi
						;;
					O*)
						# Focused Occupied Workspace
						wm_infos="${wm_infos}%{F#$purewhite}%{B#$magenta}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}"
						;;
					F*)
						# Focused Free Workspace
						wm_infos="${wm_infos}%{F#$purewhite}%{B#$green}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}"
						;;
					U*)
						# Focused Urgent Workspace
						wm_infos="${wm_infos}%{F#$purewhite}%{B#$red}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}"
						;;
					o*)
						# Occupied Workspace
						wm_infos="${wm_infos}%{F#$purewhite}%{B#$bg}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}"
						;;
					f*)
						# Free Workspace
						wm_infos="${wm_infos}%{F#$bg}%{B#$bg}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}"
						;;
					u*)
						# Urgent Workspace
						wm_infos="${wm_infos}%{F#$purewhite}%{B#$yellow}%{A:bspc desktop -f ${name}:}%{A4:bspc desktop -f prev:}%{A5:bspc desktop -f next:}$Padding${name}$Padding%{A}%{A}%{A}%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm_infos}${music}%{c}${title}%{r}${wifi}${volume}${battery}${date}${clock}"
done
