#! /bin/sh

# Variables
. $HOME/bin/colr

# Appearance
bspc config border_width                 3
bspc config window_gap                   0
bspc config normal_border_color		"#$bg"
bspc config focused_border_color	"#$magenta"
bspc config presel_border_color 	"#$purered"

# Configuration
bspc config split_ratio                  0.5
bspc config borderless_monocle           true
bspc config gapless_monocle              true
bspc config focus_by_distance            true
bspc config focus_follows_pointer        true
#bspc config top_padding                  20

# Workspaces
bspc monitor -d 1 2 3 4 5 

# Rules
	# Class
#bspc rule -a Firefox desktop=^2
bspc rule -a file-roller floating=on
bspc rule -a Kodi desktop=^4
bspc rule -a leafpad floating=on
bspc rule -a mpv desktop=^3
bspc rule -a pcmanfm floating=on
bspc rule -a sxiv floating=on

	# Workspace
bspc desktop ^3 -t floating=on

# Startups Programs
xsetroot -cursor_name left_ptr
numlockx
unclutter --fork|-b
walls.sh &
redshift &
compton &
urxvt &
