#!/bin/bash

# Herbstluftwm

# Setup
hc() {
	herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all
hc mouseunbind --all

# Variables
. $HOME/bin/colr
mod=Mod4

# Tag/Wkspaces
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

	# Workspaces
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$mod-$key" use_index "$i"
        hc keybind "$mod-Shift-$key" move_index "$i"
    fi
done

# Colours
hc set window_border_active_color "#$magenta"
hc set window_border_normal_color "#$bg"

# Theme
hc set smart_frame_surroundings 1
hc set frame_normal_opacity 	0
hc set frame_bg_transparent 	1
hc set frame_border_active_color "#$magenta"
hc set frame_border_normal_color "#$bg"

# Keys
	# Quit, close, create
hc keybind $mod-Return 	spawn urxvt
hc keybind $mod-Shift-e quit
hc keybind $mod-Shift-q close
hc keybind $mod-Shift-r reload

	# Focus
hc keybind $mod-h	focus left
hc keybind $mod-j	focus down
hc keybind $mod-k	focus up
hc keybind $mod-l	focus right
hc keybind $mod-Tab 		cycle_all +1
hc keybind $mod-Shift-Tab 	cycle_all -1

	# Move
hc keybind $mod-Shift-h		shift left
hc keybind $mod-Shift-j     shift down
hc keybind $mod-Shift-k     shift up
hc keybind $mod-Shift-l     shift right

	# Resize
resizestep=0.05
hc keybind $mod-Control-Shift-h       resize left 	+$resizestep
hc keybind $mod-Control-Shift-j       resize down 	+$resizestep
hc keybind $mod-Control-Shift-k       resize up 	+$resizestep
hc keybind $mod-Control-Shift-l       resize right 	+$resizestep

	# Split
hc keybind $mod-v       split   right   0.5
hc keybind $mod-b       split   bottom  0.5
hc keybind $mod-q remove

	# Float, fullscreen etc.
hc keybind $mod-f fullscreen toggle
hc keybind $mod-s floating toggle
hc keybind $mod-p pseudotile toggle
hc keybind $mod-r remove
hc keybind $mod-space cycle_layout 1

	# Mouse
hc mousebind $mod-Button1 move
hc mousebind $mod-Button2 zoom
hc mousebind $mod-Button3 resize
hc set focus_follows_mouse 1

# Rules
hc rule focus=on
hc rule class=9menu manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# Finish-up

	# Just in mufukin case
hc unlock

herbstclient set tree_style	'╾│ ├└╼─┐'

# Startup
sxhkd -c ~/.config/sxhkd/herb &
walls.sh &
hc pad 0 20 0 0 0
bitbar &
compton &
